name: 'Jenkins Job Trigger'
description: 'This action allows triggering Jenkins Job and wait for its result.'
inputs:
  job_url:
    description: 'Url to jenkins job'
    required: true
  user_pass:
    description: 'User password'
    default: ''
    required: false
  wait:
    description: 'Should action wait for job to finish?'
    default: 'false'
    required: false
  params:
    description: 'Parameters as JSON string for parametrized jobs'
    required: false
    default: ''
  log:
    description: 'Should I get Jenkins Job log stream'
    required: false
    default: 'false'
outputs:
  url: 
    description: 'Url to job item'
  result:
    description: 'Result of job execution. Can be success or failure'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'git-branch'  
  color: 'blue'