name: "units-test"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      id: jenkins
      with:
        job_url: https://ci.10clouds.com/job/10C/job/GHATest/
        user_pass: ${{ secrets.jenkins }}
        wait: 'true'
        log: 'true'
        params: '{"env_name":"sputnik", "deploy": "true" }'

    - run: |
        echo "Jenkins job execution url is ${{ steps.jenkins.outputs.url }}"
        echo "Jenkins job result is ${{ steps.jenkins.outputs.result }}"
